# Generated by Django 5.1.4 on 2026-03-17 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('imports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='graderecord',
            name='source_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_records', to='imports.sourcefile'),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academics.student'),
        ),
        migrations.AlterUniqueTogether(
            name='graderecord',
            unique_together={('student', 'classroom', 'academic_year')},
        ),
    ]
