# Generated by Django 5.1.4 on 2026-03-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_pg_trgm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graderecord',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
