# Generated by Django 5.1.4 on 2026-03-17 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_pg_trgm'),
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcefile',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_files', to='academics.academicyear'),
        ),
    ]
